### ISSUE TITLE
Small favicon issue

### ISSUE THREAD

**Issue by harrieklomp** [opencaching/opencaching-pl#1145]
Somehow the favicon has been changed in my tab with links to other OC nodes (FireFox). This did happen after one of latest commits.
It is not a big thing but it changed somehow :-)

![selectie_106](https://user-images.githubusercontent.com/1060518/29486677-12e1a53e-84ec-11e7-970a-fc3a81364305.jpg)

**Comment by deg-pl** [comment]
I can't reproduce it
![tmp](https://user-images.githubusercontent.com/13884863/29489950-713abcb0-852d-11e7-92d1-e255dab9df4a.png)

**Comment by harrieklomp** [comment]
Strange.
On another computer i see the correct favicon. Looks like a local FF problem.
Then i close this issue.
Thanks anyway :-)

**Comment by andrixnet** [comment]
AFAIK there is a generic `favicon.ico` _(windows icon format)_ file in the root directory of the site. This was historically a default for Microsft Internet Explorer, before personalizations using HTML like: 
`<link rel="shortcut icon" href="/images/oc_icon-ro.png">`

This file still exists _(and removing it may result in increasing error.log filesize due to 404 errors)_ and should not be removed. 
If the above HTML is missing, or the image cannot be retrieved, the browser may revert back to ask for `favicon.ico`. However this file is and can be only one, and uses the generic "G+yellow_sun" opencaching logo.

Also, as I've seen some times inconsistent behaviour by Firefox regarding what icon it saves in the bookmarks.
