### ISSUE TITLE
XSS vulnerability in OCPL log handling code

### ISSUE THREAD

**Issue by andrixnet** [opencaching/opencaching-pl#1218]
It is possible to inject XSS into OCPL logs. 
An example here: https://github.com/opencaching/okapi/issues/412#issuecomment-329806320

Not sure how much if further OKAPI filtering is necessary, or just OCPL website code.

**Comment by following5** [comment]
This is due to a bug in handling HTML entities. It allows to bypass the HTML filters and inject any kind of HTML code into the logs.

If you enter e.g. `<div>` in the editor, it will be stored in the database as `&lt;div&gt;`. When this log is displayed, this HTML code from the database should simply be copied to into the HTML output. Instead, the OCPL code does a [htmlspecialchars_decode](https://github.com/opencaching/opencaching-pl/blob/master/lib/userInputFilters/userInputFilter.php#L136)() which restores the original `<div>`. This is inserted into the output and destroys the page layout for all the previous logs. See my example log for [OP28F9](https://opencaching.pl/viewcache.php?cacheid=10492).

This bug also messes up any valid log entry text which looks like a HTML element. Eg if you log this:

`I assumed A<B and C>D when calculating the coordinates.`

then it will be displayed as: "I assumed A**D when calculating the coordinates.**" The `<B and C>` is parsed as a HTML `<b>` with the empty attributes `and` and `C`.

When log-submiting was implemented in OKAPI, a [workaround](https://github.com/opencaching/okapi/blob/master/okapi/services/logs/submit/WebService.php#L332) was done for OCPL logs: OKAPI _double encodes_  the HTML entities `<`, `>` and `&` as `&amp;#60;`, `&amp;#62;` and `&amp;#38;`. This neutralizes the htmlspecialchars_decode() which is done before display. When retrieving OCPL logs, OKAPI will also [decode](https://github.com/opencaching/okapi/blob/master/okapi/core/Okapi.php#L1077) it's double-encoding.

To sum it up:
* htmlspecialchars_decode() should NOT be done for log entry texts, but:
* If the htmlspecialchars_decode() is removed, it will break `<`, `>` and `&` characters in existing OKAPI logs.
* If the htmlspecialchars_decode() is removed,  it may also break existing logs which used this bug as a feature, e.g. users inserted HTML code directly in the editor.

So I guess this will need some flag in the `cache_logs` table to distsinguish between old and new logs, and htmlspecialchars_decode() is omitted only for the new logs. And maybe some additional filtering is needed for the old logs.

Any fix should be synchronized with the OKAPI implementation.

**Comment by following5** [comment]
I will try to fix this.

**Comment by following5** [comment]
> this will need some flag in the `cache_logs` table to distsinguish between old and new logs

`cache_logs`.`text_html` can be reused for that.

* 0 = html generated from plain text
* 1 = original html, will be htmlspecialchars-decoded
* 2 (new) = original html, will not be htmlspecialchars-decoded

**Comment by kojoty** [comment]
> this will need some flag in the cache_logs table to distsinguish between old and new logs
> cache_logs.text_html can be reused for that.
> 
> 0 = html generated from plain text
> 1 = original html, will be htmlspecialchars-decoded
> 2 (new) = original html, will not be htmlspecialchars-decoded

hmm.. I think I don't have a deep understanding of this issue but let me catch: why we can't just fix all existed comments in DB and fix the code to get the clean new one and avoid any "modes" of handling comments content?

**Comment by deg-pl** [comment]
> why we can't just fix all existed comments in DB and fix the code to get the clean new one and avoid any "modes" of handling comments content?

Exactly! 100% right!

**Comment by following5** [comment]
> why we can't just fix all existed comments in DB 

Not the comments in the DB are broken, but the code which prepares them for display.

Why can't we just fix the broken code, i.e. discard the `htmlspecialchars_decode`? 

Because there very likely are logs in the database which are adjusted to the broken code (users entered their HTML directly in TinyMCE instead of the HTML edit window). So if the code is fixed, it will break those logs.

Can we detect those logs and do something about them, so that the code can be fixed?

I don't think there is a reliable way to detect all of them, and to distinguish them from "harmful" logs like those in [OP28F9](https://opencaching.pl/viewcache.php?cacheid=10492), which should be excluded from this logtext overhaul.

If you still want to go for this solution:
* I suspect that earlier versions of OCPL code double-encoded the log entries HTML, then this `htmlspecialchars_decode` would make sense. This old logs would need special treatment (one-time html-decoding).
* OKAPI logs also will need special treatment (one-time decoding of the OKAPI woraround, as mentioned above).

This is complicated and will take time. My proposed code change (26145ce9) would _immediatly_ fix this security issue. And it would not hinder in any way the database `log_text` migration as a second step. Actually it would _support_ it, because it allows to do the migration step by step: The logs that are updated would be changed to `text_html`=2. If no `text_html`=1 logs are left, the added code (just a few lines) could be discarded.
