### ISSUE TITLE
GPX Attribute IDs conflict with OCDE IDs

### ISSUE THREAD

**Issue by following5** [opencaching/opencaching-pl#1242]
I just noticed that the OCDE GPX attribute schema has been [adopted](https://github.com/opencaching/opencaching-pl/blob/d5bcc8a155d254c538cc1437afb9e0fe51b20906/lib/format.gpx.inc.php#L262) in OCPL code: Attributes which are not known to Groundspeak are added with ID +100 to the GPX file. It looks like this was added by @andrixnet in April 2017.

However, some of these IDs conflict with the IDs which are in use for years at Opencaching.de:

* 143: OCDE "Breeding season", OCPL "GeoHotel" (wrongly labeld as "Quick cache" [here](https://github.com/opencaching/opencaching-pl/blob/d5bcc8a155d254c538cc1437afb9e0fe51b20906/lib/format.gpx.inc.php#L276))
* 150 OCDE "Cave equipment", OCPL "Audio file"
* 153 OCDE "Aircraft required", OCPL "USB Dead Drop cache"
* 154 OCDE "Investigation", OCPL "Near a Survey Marker"

Then, there are these assignments with multiple conflicts:

OCDE 156 "Arithmetical problem":
* opencaching.ro/nl/uk 8 => 156 "Letterbox cache"
* opencaching.pl 56 => 156 "Letterbox cache"
* opencache.uk 156 => 156 "Aircraft required"

OCDE 157 "Other cache type":
* opencache.uk 57 => 157 "Other cache type":
* opencache.uk 157 => 157 "Rated on Handicaching.com"

OCDE 158 "Ask owner for start conditions":
* opencache.uk 58 => 158 "Ask owner for start conditions"
* opencache.uk 158 => 158 "Contains a Munzee"

This is a mess. It prevents adding the OCPL attributes to Okapi GPX using the [attrs=gc_ocde:attrs](https://www.opencaching.de/okapi/services/caches/formatters/gpx.html) option, and it prevents to write GPX tools which correctly process all Opencaching attributes. (I will add a second post with a proposal how to solve this.)

**Comment by following5** [comment]
As the OCDE GPX attrib IDs are in use for years and the OCPL IDs - as I understand it - have been defined recently, I suggest to reassign the 8 conflicting OCPL attribs to some other IDs.

These can be reassigned to existing OCDE GPX IDs:
* Letterbox Cache (OCPL 8/56/156) => 108
* Aircraft required (156) => 153

The other 6 attribs could be assigned to IDs which are not and in use, e.g.
* GeoHotel (OCPL 43) => 109
* Audio file (50) => 111
* USB Dead Drop cache (53) => 112
* Near a Survey Marker" (54) => 113
* Rated on Handicaching.com (157) => 114
* Contains a Munzee (158) => 115

There are also some OCPL attributes missing in format.gpx.inc.php. They could also be mapped to either existing OCDE IDs or unused IDs.

Could you agree with this change? I would take care of the implementation, and would review the attribute lists of all OCPL sites (they are available via Okapi), so that nothing is missed. #965 and similar conflicts could also be solved, so that the result is a clean All-Opencaching GPX ID set.

**Comment by kojoty** [comment]
@following5, my opinion is simple: go ahead with it! I don't know much about this part of our code and issues around GPXs generation - it would be great if you clean up this mess :) Thanks for that!

BTW: @andrixnet prepared some time ago common wiki [wiki.opencaching.eu]([wiki.opencaching.eu) with the intention of documenting common settings -  maybe it could be a good idea to explain it there... @andrixnet am I right?

**Comment by following5** [comment]
I will try to fix the bugs and conflicts and make a PR.

For the global reference documentation of Opencaching attributes, I think [this](https://github.com/opencaching/okapi/blob/master/okapi/services/attrs/attribute-definitions.xml) would be the best place. From there, e.g. a table for https://wiki.opencaching.eu/index.php/Cache_attributes could be generated.

**Comment by following5** [comment]
When this issue is resolved, I will add some explanation to https://wiki.opencaching.eu/index.php/Cache_attributes:
* How to assign IDs to a new attribute?
* How to harmonize attribute IDs on different OC sites?

**Comment by andrixnet** [comment]
I propose a more radical overhaul, that will bring consistency across OCPL and OCDE and greatly simplify exports and OKAPI and exchanging data. 
It requires a bit of cooperation between OCPL and OCDE developers and each node admin because there will be changes in the data.

Here is my proposal _(for a complete overhaul)_: 
- all OC attributes that have equivalent meaning to a GC attribute to use the same numeric ID
_(while the meaning is equivalent, the exact wording of it's name need not be the same. examples are "bring your children / suitable for children / kids friendly / etc")_
- all OC attributes that have equivalent meaning to a negated GC attribute to use the same numeric ID with 99X prefix, where X is the hundreds digit from the GC attribute ID, currently 0, but allowing to be expanded. _(for example: "available 24/7" is ID 13. "NOT available 24/7" to be ID 99013.)_
- all OC attributes that have equivalent meaning on both PL and DE branches to have numeric IDs in the range 1000 - 1999
- all OC attributes that are PL branch specific to have numeric IDs in the range 2000 - 2999
- all OC attributes that are DE branch specific to have numeric IDs in the range 3000 - 3999
- all OC attributes that have the meaning of a negated OC attribute to use the same numeric ID on the least significant 3 digits, the fourth digit be the branch designator (according to applicability) and the fifth (most significant digit) be 9. 
(hypothetical generic example: "available during high tide" ID 2141 - PL branch (UK), "NOT available during high tide" ID 91141 - all branches)

The only special processing to handle OC/GC differences might be regarding the negated GC attribute to set GC specific negation with non-prefixed ID in GPX file. The introduction of <oc:attribute> in GPX export is very helpful in this regard too.
All IDs documented properly at https://wiki.opencaching.eu/index.php/Cache_attributes 

-----------------------------
What does this acomplish: 
1. a consistent export of data with non-overlapping numerical identificators regardless of the source site
2. a consistent and well documented set of data for third party application builders to rely upon
2. a consistent export of data compatible with GC aware apps

**Comment by andrixnet** [comment]
Roadmap to acomplish this: 

1. collect all existing information from all nodes about attributes
2. decide and inform all nodes and developers to put on hold any future changes to attributes until this is fully implemented and deployed
3. renumber all attributes (and create well documented correspondency tables); document new scheme at https://wiki.opencaching.eu/index.php/Cache_attributes along with deployment schedule.
4. implement the code changes
5. create SQL files to alter the database definition tables and cache<=>attrib mapping tables
6. test
7. make simulated deployment
8. coordinate with all node admins for production deployment
8a. OC node stops syncing to repository (at least PL branch based nodes)
8b. OC node goes into maintenance mode
8c. database changes are applied
8d. OC node updates to code changes 
8e. OC node resumes syncing to repository (where applicable)
8f. OC node resumes normal operations
9. make documentation updates (including publishing the remapping table, if needed by third party)
10. point third party developers to https://wiki.opencaching.eu/index.php/Cache_attributes

**Comment by andrixnet** [comment]
The above roadmap is the complete picture of what I had devised in time for bringing consistency to the attributes chaos. Parts of it I tried to apply when I started reworking UK attribs. 

Any further attribute changes must then follow the documentation at https://wiki.opencaching.eu/index.php/Cache_attributes which will include the rules I described above and will ensure having a consistent set.

**Comment by following5** [comment]
That's all off-topic here. This issue is just about the **GPX IDs**, which are inserted into `<groundspeak:attribute>` in the GPX files. There _now_ are problems with that IDs that should be fixed as soon as possible, independently from your efforts to eventually introduce unique OC IDs across all sites.

So can you please move that to another thread?

**Comment by andrixnet** [comment]
Please do so on my behalf
