### ISSUE TITLE
last_login not updated

### ISSUE THREAD

**Issue by harrieklomp** [opencaching/opencaching-pl#1269]
After last commit for new login page the column "last_login"  in table "user" is not updated anymore in DB.

**Comment by kojoty** [comment]
hmm... I check it in details in the evening but I remember I looked at this and it worked.. let me see...

**Comment by kojoty** [comment]
@harrieklomp , OK, I've checked this and it seems that I didn't put update of user.last_login in code because there was DB trigger which updates this - see https://github.com/opencaching/opencaching-pl/blob/master/docs/sql/triggers_and_procedures/sys_sessions.sql

But this trigger works only on session creation - what can be really rare for users with "permanent login".
I need to remove this trigger and update last_login in code.

Fix will be delivered soon.

**Comment by kojoty** [comment]
@harrieklomp, it should be fixed now - please check and reopen if there is anything more to do.

**Comment by harrieklomp** [comment]
Now it works again. Thanks!!!!
