### ISSUE TITLE
Rewrite autoarchive mails using new Email object

### ISSUE THREAD

**Issue by deg-pl** [opencaching/opencaching-pl#1279]
Autoarchive mails are send directly via mb_send_mail, not Email object. Looks differently. Should be rewriten to use common email interface.

Related with #286

**Comment by rapotek** [comment]
@deg-pl as you know I just wanted to modify this file by myself. It is not only the Email object including, but the whole file needs refactoring (queries far from being optimal, mandatory logentries usability etc). Because of new configuration settings introduction neccessity, I think @kojoty should tell us how to make a proper configuration to avoid complaints that it should not be done this way.

**Comment by deg-pl** [comment]
Ok.

**Comment by kojoty** [comment]
>  to avoid complaints that it should not be done this way.

:) YEAH! I feel i like to work with you !

**Comment by rapotek** [comment]
@kojoty wiem, że nie masz czasu (ja z resztą też nie mam), ale może warto by było, abyś przynajmniej opisał w jakim kierunku powinien iść konfig. Wiem, że obecny Ci się nie podoba, ale nie wiem dlaczego i co chcesz osiągnąć. A jak pomyślę o jakimkolwiek refaktoringu, to blokuje mi się na tym temacie.

**Comment by kojoty** [comment]
postaram sie w poniedziałek coś naskrobać OK?

**Comment by rapotek** [comment]
ok :)

**Comment by deg-pl** [comment]
@rapotek miej od razu świadomość #682 - można jedno i drugie zrobić za jednym razem, bo to podobny kawałek kodu.
