### ISSUE TITLE
Stats page filter might use hardcoded strings

### ISSUE THREAD

**Issue by andrixnet** [opencaching/opencaching-pl#1344]
http://www.opencaching.ro/articles.php?page=s2

![stat-s2](https://user-images.githubusercontent.com/3382777/35036339-b606e6f0-fb7c-11e7-81b8-4974eda5128c.png)

**Comment by andrixnet** [comment]
BTW, what is "shared place" vs "rank"?

**Comment by following5** [comment]
The translations at OC RO now look ok.

@andrixnet 
> BTW, what is "shared place" vs "rank"?

The "shared place" is the position in terms of total users count, while for the "rank" places, users with same number of finds are counted only once.

I am also confused by that, because of the term "shared place", and because that is calculated in an unusual way: Instead of showing the lowest possible number for all users, it shows the highest.

**Comment by following5** [comment]
If any, the *first* column is the "shared rank".
