### ISSUE TITLE
GeoCacheCommons::CacheIconByType doesn't support *-owner images

### ISSUE THREAD

**Issue by deg-pl** [opencaching/opencaching-pl#1455]
GeoCacheCommons::CacheIconByType() and GeoCache->getCacheIcon() doesn't add "-owner" to icon name when user is owner of the cache. This can be supported via $logstatus param (CacheIconByType()) and minor fix in getCacheIcon().
Example icon without -owner suffix:
![](https://opencaching.pl/tpl/stdstyle/images/cache/traditional-s.png)
And the same icon with -owner suffix:
![](https://opencaching.pl/tpl/stdstyle/images/cache/traditional-s-owner.png)

**Comment by rapotek** [comment]
I've made some review of `tpl/stdstyle/imagea/cache` directory. Here are the results (text instead of image means there is no icon with the given name):
![gcc_cibt](https://user-images.githubusercontent.com/17698165/37338270-45a23f48-26b7-11e8-854b-25d9860db9b8.png)
![no_gcc_cibt](https://user-images.githubusercontent.com/17698165/37338280-51e0ec50-26b7-11e8-91cd-107a5b4873ac.png)
![who_knows](https://user-images.githubusercontent.com/17698165/37338293-617b054c-26b7-11e8-8611-de611e9ea9ab.png)
![16x16](https://user-images.githubusercontent.com/17698165/37338305-68b767a6-26b7-11e8-86f6-b2d57f68611c.png)
![22x22](https://user-images.githubusercontent.com/17698165/37338373-96d2ef02-26b7-11e8-8d43-6ef041f3695c.png)
![24x24](https://user-images.githubusercontent.com/17698165/37338388-9b5c7566-26b7-11e8-9190-ee57d1396fd0.png)

Next to the listed above there are two images: `arrow_left.png`, containing a green arrow pointing left and `preview.png` containing most of icons but some already outdated.

There is also a subdirectory `kml` containing more images prepared for inclusion into KML export output.

The main icons are created in the same manner: the status/log elements are added to the base icon (including fade effect). I wonder if it would make sense to create the icons from the base image and status element in the dynamic files directory or using JS on the client side?

**Comment by kojoty** [comment]
@rapotek: wow!
