### ISSUE TITLE
Meeting the requirements General Data Protection Regulation Law

### ISSUE THREAD

**Issue by deg-pl** [opencaching/opencaching-pl#1464]
From the 25'th of May 2018 we have to meet requirements of the General Data Protection Regulation Law (https://www.eugdpr.org/). We have specific guidelines prepared what needs to be changed in the code and we will change it. **But I'm nearly sure, that ALL of OC nodes should change their Terms of Use**. From 25.05.2018 our code will enforce acceptance of new Rules (or will deactivate account).

@harrieklomp @andrixnet @Amberel Do you have new rules? Are work on it ongoing?

**Comment by harrieklomp** [comment]
I have some questions and perhaps some suggestions.

- Will there be a standard Terms of Use for all nodes? If yes, this could be in English and must be translatable.
- Are there separate Terms of use for the main site and for the forum? Most nodes do have a forum and/or blog etc.
- Are other nodes be informed about the progress? Perhaps visualisation on Deg's development site?

**Comment by deg-pl** [comment]
@harrieklomp 
Our OC Team is working on changes in the regulations. I am afraid that each country will need separate regulations. GDPR is Europe-wide law, but every european country has executive law to meet local standards. For example - GDPR defines the range between 13 and 16 years of age when parents' consent for the use of service is required. The Polish law defines this age as 13. I do not know how it is in your's country. OC PL regulations contain many references both to Polish law and the specificity of OC PL (i.e. we has no virtual caches, our OC Team consists of a Technical Team and a 16-person Centurm for Geocaher Service)

BUT :) our OC Team prepares document with most important changes - in English, and will share it with other OC nodes.

**Comment by andrixnet** [comment]
We will have to research this in depth.

**Comment by harrieklomp** [comment]
On OCNL i have made a new wiki page with GDPR guide (in Dutch) on http://wiki.opencaching.nl/index.php/Privacyverklaringen. This is done because there is a lot to explain to user about this subject and it is not recommended to use some lines in only "Terms of Use". There are a lot of standard forms on internet who does explain (Polish, English or Romanian) witch have all text in it to use for this. Perhaps only change sitenames  on this form.
I would like to suggest to use on registration page two links "Terms of Use" and "Privacy statement". This "Privacy statement" should also added to footer.

**Comment by harrieklomp** [comment]
Because of this GDPR there should also be a solution to remove a user who does not accept the GDPR rules or has not the age of 13 or 16. If a user sends a e-mail that he wants to remove his account, than Admins should be able to do this via Admin --.> Managing the user. The easy part is when this user has no logs or made caches.
In this "managing the user" page should be another button who does remove user including all logs and his caches. When use such a button there should be a confirmation button too. This to prevent unwanted removing a user ;-)

**Comment by deg-pl** [comment]
@harrieklomp I know.
But now I have a lot of work and have no time for OC.

GDPR doesn't require automatic removing user, so for about 1 month it will be done manually. I'll create "remove account" function, but in the second half of June.

GDPR rules doesn't require to remove logs/caches by admin. User can do it by himself.

**Comment by kojoty** [comment]
@deg-pl is there anything more to do?

**Comment by deg-pl** [comment]
We have not anonymisation procedure. I make new issue - #1666, so I close this.
