### ISSUE TITLE
Dead link

### ISSUE THREAD

**Issue by kumy** [opencaching/opencaching-pl#1475]
https://github.com/opencaching/opencaching-pl/blob/4c2b5b81a846d19a3bef777e1e729a8ae07ef7fb/lib/languages/fr.php#L62

Link to http://www.9key.com/selector.asp is dead

**Comment by kojoty** [comment]
Hi, Thanks for the information.

Please note that generally our french translation is not maintained for a very long time - that's why it is disabled at most opencaching sites which based on our code (I mean pl, ro, nl, uk nodes). We don't have anyone who know French enough to provide such translation of the service so this is in fact dead code now.

**Comment by kumy** [comment]
Hi, Harrie solicited me for the French translation. @kojoty do you have the translations files available on a dedicated translation platform like crowdin.com?

**Comment by harrieklomp** [comment]
I will pepaire things for French translations file.

**Comment by kumy** [comment]
@harrieklomp I've opened pull request #1476 with my current WIP, may you please take care of it when you'll "prepare things for French translations file". Thanks

**Comment by kojoty** [comment]
I close this - I assume this is no longer an issue.
