### ISSUE TITLE
UserAuthorization/login page: 'Register' button leads to error page

### ISSUE THREAD

**Issue by DorotkaMakotka** [opencaching/opencaching-pl#1534]
'Register' button on login page doesn't work properly. Similar button in the upper right corner of the page seems to work well.

![register](https://user-images.githubusercontent.com/19299162/40141866-682903f8-5957-11e8-86a3-15ae21f541e7.PNG)

**Comment by Moris299** [comment]
Hej! :)
Nie mam pewności ale patrząc na szybko wystarczy zamienić w pliku
_opencaching-pl/tpl/stdstyle/userAuth/loginPage.tpl.php_

w linijce 27 zamienić
`<?=SimpleRouter::getLink('UserAuthorization', 'register')?>`
na 
`<?=SimpleRouter::getLink('UserRegistration')?>`

jeśli się mylę to przepraszam, dopiero ogarniam kod i nie zainstalowałem jeszcze wirtualnej maszynki do testowania :) Zostawiam to bardziej obytym w kodzie do sprawdzenia, pozdrawiam :)

**Comment by deg-pl** [comment]
@Moris299 Bardzo dobrze myślisz - brawo. To pewnie mój błąd, bo początkowo wrzuciłem rejestrację do UserAuthorizationController, potem Kojot zaproponował zrobienie osobnego kontrolera i pewnie w tym miejscu nie zauważyłem, że też trzeba poprawić.

Rób zatem szybko maszynę wirtualna i wrzucaj pierwszą Twoją poprawkę! Trzymam kciuki, w razie problemów technicznych - pisz. Choć chyba raczej do @kojoty , bo jest świeżo po grzebaniu w maszynie wirtualnej.

Bardzo się cieszę, że znalazłeś chwilę, by do tego zerknąć.

**Comment by deg-pl** [comment]
Fixed by commit 6e15e4bbde7fc47448c5d2eaae343571fdc9580b
Thanks @Moris299 

@Moris299 Nawet nie zauważyłem, że dorzuciłeś PR'a. Brawo!
Github ma fajną cechę (zerknij tu https://help.github.com/articles/closing-issues-using-keywords/) - możesz np. w commicie (lub PRrze) dorzucić "fixes #1534" i po merge issue sam się zamknie, jednocześnie wiążąc issue z commitem (lub PRem).
Dzięki jeszcze raz i liczymy na więcej! :)
