### ISSUE TITLE
Strange behaviour logpictures

### ISSUE THREAD

**Issue by harrieklomp** [opencaching/opencaching-pl#1565]
I notice a strange behaviour with log pictures when not logged in or logged in as owner.

Not logged in shows this:
![selectie_184](https://user-images.githubusercontent.com/1060518/41255701-b46b89dc-6dc7-11e8-9f81-dded89ef3cc5.png)

Logged in as owner:
![selectie_185](https://user-images.githubusercontent.com/1060518/41255719-c404d5e2-6dc7-11e8-8bde-490807753962.png)

This is at https://www.opencaching.nl/viewlogs.php?logid=4908

**Comment by following5** [comment]
That's a legacy OCDE bug. It is caused by different heights of elements in conjunction with [float:left formatting](https://github.com/opencaching/opencaching-pl/blob/736c1e6258af5de45ee072a4c887106f5bf5c2f8/tpl/stdstyle/css/style_screen.css#L973).

[This](https://github.com/OpencachingDeutschland/oc-server3/commit/63539d0) was the OCDE fix, but that works only if the picture blocks have a fixed width.
