### ISSUE TITLE
Email sending subsystem to support multiple email addresses in config

### ISSUE THREAD

**Issue by andrixnet** [opencaching/opencaching-pl#2116]
Configuration has several emails defined for each site. 
AFAIK at this time only one email address is permitted for each configuration variable. 

I request that it be possible to configure multiple email addresses for each variable (such as `$config['technicalNotificationEmail']`). 

_One reason being, at least for technical matters, developers can get notification from each site (and that email be aliased to a group), but also the site admin receive notifications for his site only._

Important: this request does not apply to user account emails (stored in database).

**Comment by kojoty** [comment]
I think it's quite easy to implement - I can do that soon.

**Comment by kojoty** [comment]
This is ready for technicalNotificationEmail in #2118 (which is internal only address), but for other email addresses (RT/OcTeam) there is a problem because these addresses are displayed for the users (there are such views) - then we can display many addresses... so please use some external alias there.
