### ISSUE TITLE
OC Poland not updated

### ISSUE THREAD

**Issue by harrieklomp** [opencaching/opencaching-pl#217]
It looks that the Polish site is not (automatic) updated anymore. After a commit the Polish site does not show any change. The Dutch and Romanian site does show the committed changes on the site.
Please take a look at this!!!!!

**Comment by kojoty** [comment]
Harrie, Thanks for the information. I'll try to take a look at this and resolve the issue.

**Comment by wloczynutka** [comment]
I guess that opencaching.pl is not pinned to this repositorium anymore.

**Comment by andrixnet** [comment]
I know this is collateral information, but I have to ask it: what will the foreseeable future be for opencaching-pl project and opencaching.pl website? (and I am specifically naming these two entities distinctly)
Thank you.

**Comment by kojoty** [comment]
I think Lza (wloczynutka) is too much pessimistic. Our project is on the "bend" because of personal conflicts but I believe this is not the end. Right now we have elections in oc.pl community (yeah there is a democracy!) and I believe after it (more-less at the beginning of the next year) we will know much more. Till that please be optimistic. :)

BTW. I checked and currently one of our administrators disabled automatic sync with github - I don't know the reason, but I believe this is temporary.

**Comment by harrieklomp** [comment]
Until than, i will try to make the site more international and solve some issues :-)

**Comment by wloczynutka** [comment]
*Code source is independend and open. Everyone can help developing it. You
can also search for programmers who are able to do features.*

**Comment by harrieklomp** [comment]
It is not only features that are welcome. There are also some issues that needs, or would be nice to be solved. Like you (Lza) can help with that because you have made some nice and great features and you know how some of these issues can be solved or implement these. Let be honest, good programmers with free time are hard to find and if there is a programmer they loose interest in time.

**Comment by wloczynutka** [comment]
resolved
