### ISSUE TITLE
Newly added spoiler images display as normal images.

### ISSUE THREAD

**Issue by areckisOC** [opencaching/opencaching-pl#2178]
New spoilers are not hidden.

**Comment by kojoty** [comment]
hmm... yes something is wrong here - I will take a look at this today

**Comment by kojoty** [comment]
I've checked the issue and two "fixes" are necessary:
- editpic script needs to run "regenerate" method for edited picture to - thumbnails need to be deleted and generated again then in the proper place
- at the first time after thumbnail generation the image is display - instead of "spoiler" banner - but this is only o the first view - next everything is all right

**Comment by mzylowski** [comment]
Editing issue in real life - old quiz image is replaced by new one. Thumbnail is still old, but after click the new picture appear in full resolution - https://opencaching.pl/viewcache.php?wp=OP816N

**Comment by kojoty** [comment]
hope it's fixed now. close it.
