### ISSUE TITLE
OCNA newcaches.php broken

### ISSUE THREAD

**Issue by andrixnet** [opencaching/opencaching-pl#2262]
On OCNA ( https://www.opencaching.us ) the page showing newest caches is broken. 
The menu link is https://www.opencaching.us/newcaches.php
The result is an error page that explains very little, not even a HTTP error code. Looking at the server logs I identified it as a 403 error. 

Further investigation leads me to suspect changes in the configuration subsystem, since on OCRO the link points to /Cache/newCaches though I haven't changed anything in this regard as site-admin.

**Comment by kojoty** [comment]
Where is that link. I checked and right side menu contains the right link: 
https://www.opencaching.us/Cache/newCaches

**Comment by andrixnet** [comment]
Logged in user, under "Additional Menu", link for "new caches"

**Comment by kojoty** [comment]
it seems this is some local chanage in the code on OCUS server not pushed to server
There is no config for OCUS so the default file shoudl be used there: https://github.com/opencaching/opencaching-pl/blob/master/config/menu/additionalPages.default.php

and there is aright link: 
`    'mnu_newCaches' => SimpleRouter::getLink(CacheController::class, 'newCaches'),`

Do you have an access to OCUS server?

If anyone store some configs locally instead of delivering to the repo it is a short way to such bugs...
Configs in repo are easy to maintain for developers and we can update them if we need to chanage something

Only temporary configs or non-public data should be in local configs.

**Comment by andrixnet** [comment]
I've found a file on the server I did not create myself, the online *.local.php file there.
```/config/menu
-rw-r--r-- 1 oc_us www 1972 Aug  5  2019 additionalPages.local.php```

Besides myself, only Harrie and kojoty have access. Perhaps it was created a long time ago and forgotten about.

I've changed as suggested above and retested. Now it works ok.

Thank you very much, without your help I doubt I would have identified it in the near future.
