### ISSUE TITLE
Limits on cache_visits2 table

### ISSUE THREAD

**Issue by andrixnet** [opencaching/opencaching-pl#2305]
I just discovered that the `cache_visits2` table seems to grow indefinitely, like a log without rotation. 

Some sort of limit/rotation should be placed on it's growth. 

If this is used to count how many times the cache page was visited, some strategy should be put in place such that it's growth can be limited.

**Comment by rapotek** [comment]
OK, I looked more closely.

- In fact there can be more rows than the upper limit defined above because in "usual" case the cache is viewed by a logged in user and the user's id is stored then, but if there is no current user id, that means a cache is viewed by someone who has not logged in, the client IP is stored then. Run a select counting "valid" and "invalid" IPs and then you can compare numbers of logged-in visits against anonymous visits.
- 'C' means total visits for a particular cache while 'U' means last visit made by a particular user (or IP). The 'C' and 'U' are updated when the last visit of a cache for a current user was before given period counting from now.

So there is one thing I didn't notice before that is registering visits for not logged in (anonymous) users.

**Comment by andrixnet** [comment]
There are records going back to 2017.
So mentioned improvements would be welcomed.
