### ISSUE TITLE
Responsive mode icons, mobile redirection

### ISSUE THREAD

**Issue by stefopl** [opencaching/opencaching-pl#2340]
Responsive mode toggle icons are not loading.
```/images/misc/mobile-off.svg```
```/images/misc/mobile-friendly.svg```

Any link containing the keyword ```mobile``` will redirect to ```m.opencaching.xx```.
Is it on purpose?
Probably the problem is related to a misconfiguration of Apache Virtual Hosts or .htaccess.

Problem with:
https://www.opencaching.nl/ @harrieklomp 
https://www.opencaching.ro/ @andrixnet 

Not applicable:
https://opencaching.pl/
https://opencache.uk/

Will the .nl and .ro configuration be changed, or is it better that the icons do not contain the word ```mobile```?

By the way, on .pl and .uk a redirection is probably needed
```https://opencaching.pl/mobile/ -> https://m.opencaching.pl/``` because there is an ugly website under ```/mobile```

**Comment by deg-pl** [comment]
@stefopl /mobile/* project now is not developed and will be deleted in the future.

We also have https://www.opencaching.us/ site based on OC PL code.

**Comment by stefopl** [comment]
Since the three sites based OCPL do not load these icons, I did a PR #2341 by renaming these files.

**Comment by deg-pl** [comment]
Fixed by 9f9073e1c98e0f435439da68572d548410481e77

**Comment by andrixnet** [comment]
@stefopl 
OCRO, OCNL, OCUS have been configured with the /mobile section according to the then recommended OC site configuration (IIRC 2014). Since then I am not aware of changes in this regard. (might be wrong though). 

@deg-pl 
I know the /mobile section is very old and unmaintained. Given the advances in technology, this section (at the time dedicated to low resource mobile devices) is practically obsolete. 
However, when this will be taken out of production let's do it in a coordinated manner. Thank you.
