### ISSUE TITLE
Email notification template - logo size

### ISSUE THREAD

**Issue by andrixnet** [opencaching/opencaching-pl#2417]
Logo image in the HTML template for email notifications should have a size (either width or height but not both) defined. 

For example I am using on OCRO a SVG image which has a rather large pixel size if not restricted for display.

**Comment by stefopl** [comment]
@andrixnet 
Which email client (web, PC app, or mobile app) is having trouble with the logo? It looks fine for me in the web client and on the Xiaomi email app. 

I’ve noticed that emails from opencaching.ro are going to spam. This might be because of an incorrect sender domain oc2.opencaching.ro or issues with SPF, DKIM, or DMARC.

![image](https://github.com/user-attachments/assets/394f6ce2-361b-4aab-92a0-292944e5ee57)

**Comment by stefopl** [comment]
https://www.mail-tester.com/test-ebfdwrwhb

**Comment by andrixnet** [comment]
This is how it looks on PC, Mozilla Thunderbird email client: 
![ocro-email (thunderbird)](https://github.com/user-attachments/assets/bb3df22b-8f83-4ff3-9de7-845c3d1e3b43)

This is how it looks on PC, Yahoo! Mail web interface
![ocro-email (yahoo webmail)](https://github.com/user-attachments/assets/8302c502-3bc7-468c-a369-a131538dd99c)

This is the generated HTML source of the email: 
![ocro-email - source](https://github.com/user-attachments/assets/42ecdbc6-db74-4de6-9b87-269aa197459c)

**Comment by andrixnet** [comment]
> https://www.mail-tester.com/test-ebfdwrwhb

Thanks, I used it to improve some server settings. 

Also, that tester says: 

> Your message does not contain a List-Unsubscribe header
which I believe would be in the email template

**Comment by stefopl** [comment]
@andrixnet 

All sites except opencaching.ro use a 64x64 PNG as the logo. You can see this best on their 404 pages:
- https://opencaching.pl/404
- https://opencache.uk/404
- https://www.opencaching.us/404
- https://www.opencaching.nl/404
- https://www.opencaching.ro/404

In the Git repository, we also have a dedicated .ro PNG available: https://www.opencaching.ro/images/oc_logo-ro.png

To fix this, you just need to update ```settings.inc.php``` ```$config['headerLogo']``` on opencaching.ro to use the PNG logo.

Another option would be to replace the current SVG logo, which is 512x512,
https://www.opencaching.ro/images/icons/oc_logo-ro.svg,
with a 64x64 SVG version available here:
https://ocpl.stefo.pl/images/icons/oc_logo-ro-v2.svg
Since the current SVG isn’t in Git, it would be best if you replace it manually.

I checked in Outlook and Mozilla Thunderbird, and the 64x64 SVG displays well, but in Gmail SVGs unfortunately don’t show at all: https://css-tricks.com/a-guide-on-svg-support-in-email/ In general, SVGs are not ideal for email use, as they may not display correctly in some clients.

I suggest possible solutions:

1. Use a 64x64 PNG for the website and emails (fully supported across email clients).
2. Replace the 512x512 SVG with a 64x64 SVG (this improves support in Outlook and Mozilla Thunderbird, but not in Gmail).
3. Make a code change to use a separate logo for the website and emails (SVG for the website, PNG for emails). Is the SVG really necessary in this case?

**Comment by andrixnet** [comment]
All 3 suggested solutions are valid. 
There is another one: 

4. modify email template to specify width and height for logo. 
     (practically only width as it will resize proportionally)
     And the email display won't depend exactly on the pixel size of the image. 

My initial intention was to have a good quality (ie vector = SVG) format logo that will scale to whatever size is needed and thus use a single file for likely all purposes where the logo is wanted.

On the other hand, I see your point about display problems in GMAIL. 

Now my question changes to : how do I specify file_1 for website logo and file_2 for email template logo?

**Comment by andrixnet** [comment]
Understood. 
For now I will apply option 1. 

Thank you.

**Comment by andrixnet** [comment]
Thank you
