### ISSUE TITLE
Add date of event in balon at mapv3

### ISSUE THREAD

**Issue by kojoty** [opencaching/opencaching-pl#270]
z forum:

> Postautor: Dezerter » poniedziałek, 29 lutego 2016, 07:23
> Ot taki mały kaizen: data "rozpoczęcia" w baloniku na mapie v3 dla skrzynek typu wydarzenie.

**Comment by andrixnet** [comment]
+1

**Comment by deg-pl** [comment]
Text in polish because it is about polish translation ;)

Zastanawiam się, czy w "chmurce" powinno być wyświetlane "Data rozpoczęcia wydarzenia" czy tylko "Data wydarzenia" albo nawet "Data". Teraz chmurka niepotrzebnie jest dużej wielkości i zasłania większy obszar mapy. Wiadomo, że wydarzenie ma datę rozpoczęcia wydarzenia, a nie rozpoczęcia czegoś innego ;). Wiem, że tekst pobierany jest z date_event_label i używany również w np. viewcache.php, ale również i tam wystarczyłaby krótsza wersja. Co o tym myślicie?

**Comment by mzylowski** [comment]
Myślę że w viewcache.php powinno zostać jak jest. (Data rozpoczęcia wydarzenia). Natomiast można dorzucić do chmurki krótszy napis. W sumie przeszło mi to przez myśl. Przygotuję poprawkę.
