### ISSUE TITLE
Unmaintained translations

### ISSUE THREAD

**Issue by andrixnet** [opencaching/opencaching-pl#423]
The following language files are unmaintained (they contain only 500 strings, mostly english)
- CS
- ES
- FR
- SV

The following language file is partially mantained: 
- DE (~ 2300 out of 2600+ strings, lot's of empty lines)

Should these languages be disabled as UI language option (top right corner) ?
The unmaintained files are of no practical use.

**Comment by harrieklomp** [comment]
The German translation will be updated in time. I did find a volunteer who is willing to translate it in his own time ;-)
I will contact him again.

**Comment by andrixnet** [comment]
@harrieklomp very well. It also needs to be (re)synchronized with the maintained language files. 

Does your friend use NL or EN as base for translating?

**Comment by harrieklomp** [comment]
Mostly English, when he has questions he do ask me that.

**Comment by andrixnet** [comment]
Then please wait a bit until I finish my english strings cleanup.

**Comment by harrieklomp** [comment]
I wait until all changes have been made with language files :-)

**Comment by following5** [comment]
I can also help with German translation.

**Comment by harrieklomp** [comment]
@following5 Please notify Mambofive when you like to translate to German :-)

**Comment by following5** [comment]
Done. I think we can split up the work.

Please give some notification here when the English overhaul is done; then I will [synchronize](https://github.com/opencaching/opencaching-pl/pull/391) de.php to en.php to prepare the translation.

**Comment by andrixnet** [comment]
Will do

**Comment by harrieklomp** [comment]
I have found a person who likes to translate the Swedish translations. These translations are in progress.

**Comment by andrixnet** [comment]
Is it safe to remove non-maintained translation files?
Since opening this issue, DE translation has come up to date.

**Comment by kojoty** [comment]
Right now it is safe if for all nodes which not support such languages (in settings).
I also think there is no sense to have such translations in repo.

BTW. 
@harrieklomp, @andrixnet, @deg-pl, @mzylowski:  
I would like to postulate the change in our process of preparing translations:

- right now if I add new sentence I added EN and PL translations and give others know in PR comment that update is needed

- I think we should change it to (in my opinion) the simpler way: if I add new sentence I just add new phrase to EN language file (and to PL as well) and I add EN-translated-phrases to all other translation files and mark it by comment` /* EN */` at the end of line. Then person preparing translation has really easy work: update all lines marked by` /*EN*/` mark (and removing this mark)

- because most of our changes are minor or around only one page view I think there is no need to wait-for-response on translation change in process described above - in worst case end users will see English phrases by a few day - probably they not even detect it - we can assume that we will wait with merge only if translation changes are really significant.

PROPS of new process:
- there is no need to looking for what was changed between files etc.
- if such PR is merged before translation update end users see English phrase instead of 'TODO-no-translations...'
- there is no need to "wait"

What do you think about it?

**Comment by deg-pl** [comment]
This is a very good idea.

**Comment by harrieklomp** [comment]
This is a better solution than it was before.

**Comment by andrixnet** [comment]
very good idea. 

On the other hand, if any non-polish speaking developer makes such a change, how should the PL string(s) be written?
1. english string /* EN */
2. google translate string to PL and add /* PL */
3. other, please specify

**Comment by kojoty** [comment]
@andrixnet, I assume that every developer always:

- add proper EN translation
- proper translated phrases to language files if have competence to it (I add PL transl. you add RO transl. etc.)
- add English phrases (with` /*EN*/` mark) to all other translation files 

so there is no place for any other marks than `/*EN*/`

**Comment by harrieklomp** [comment]
Translations are now done via Crowdin.
Please reopen when needed.
