### ISSUE TITLE
Simplify the search on the top page

### ISSUE THREAD

**Issue by deg-pl** [opencaching/opencaching-pl#443]
Polish users proposed further simplify the search on the top page. It should consist of two options: geocache (working as waypoint/name) and the user (working as "Search for users" in menu). I made already rework the code on my fork. Now I would like to ask you what are you think about it. Especially @andrixnet and @harrieklomp 

![search](https://cloud.githubusercontent.com/assets/13884863/14215250/1db603fc-f842-11e5-929d-4f98a1624130.png)

**Comment by kojoty** [comment]
+1

**Comment by harrieklomp** [comment]
My opinion is that this would be too simple and we have a "Search user" in the left menu.
Like it is now we can search for user who has placed caches and who has find caches without filters. I like how it is now :+1:

**Comment by andrixnet** [comment]
I too vote @harrieklomp . The current searchbox offers tremendous help finding caches by: 
partial waypoint name
waypoint code
shorthand for waypoint code (prefix ommited)
(all put together into a single field, by a recent change, for which I am thankful). 

by:
geocacher name who hid the cache (exact name)
(all geocaches hidden by user X)
geocacher name who found it (exact name)
(all geocaches found by user X)

The focus is on getting geocaches as results. 

On the other hand, getting results for owned and found geocaches by user X in a single result set may be a bit confusing (?). 

Personally I find "search for user X" there perhaps less useful. 
Interestingly enough, sometimes I feel I'd like to have focus in the search field on page load. 

On the other hand, since this is a feature was requested by polish users, it might be introduced as a per node feature: 

settingsDefault.inc.php:
$config['node']['quick_search']['geocache_by_name'] = true;
$config['node']['quick_search']['geocache_by_finder'] = false;
$config['node']['quick_search']['geocache_by_onwer'] = false;
$config['node']['quick_search']['user'] = true;

Each node can [re]define their own preference then in settings.inc.php. 

Top-right FORM is then generated based on 4 ifs for the control fields. 
The styles for the DIV containing the form should then be redesigned to allow it to dynamically resize itself horizontally, based on the enabled options.

**Comment by deg-pl** [comment]
@andrixnet if I remember well - you prefered to remove all radio buttons and max simplyfy of search engine - see issue #131 :D 
Today I've done small voting system on FB:
![vote](https://cloud.githubusercontent.com/assets/13884863/14222650/6947c86a-f873-11e5-9ebe-ab75568d5b2f.png)
(first option is new search, second - current)
Users are searching other user's profile to see their stats or maps.

**Comment by andrixnet** [comment]
Yes, indeed. I remember.
From my point of view, the main usage difficulty was code vs. name, which you solved brilliantly https://github.com/opencaching/opencaching-pl/issues/291#issuecomment-199443161 .

Regarding my latest comments, with time, perspective has changed. I found the feature much more useful.

I understand the desire expressed by your users. 

The configurability I described above stands for allowing the nodes to set this feature according to their users' preference (see @harrieklomp above) and also allowing to reactivate a feature once found useful without recoding it (or digging into past changes) and affecting all nodes again.

Please take a look at my recent work on cache minimap and available external maps
https://github.com/opencaching/opencaching-pl/pull/454 
as examples of per node flexible functionality. 
Perhaps a similar approach (in principle) can be applied here as well.

**Comment by deg-pl** [comment]
@harrieklomp , @andrixnet 
If you want disable this feature, simply add to settings.inc.php:
$config['quick_search']['byowner'] = true;
$config['quick_search']['byfinder'] = true;
$config['quick_search']['byuser'] = false;

**Comment by mzylowski** [comment]
We can think about remove user searching from menu on the left now. We duplicate functionalities ;]
![selection_011](https://cloud.githubusercontent.com/assets/13780868/14375842/c4c66ba6-fd64-11e5-95da-05b2fe92c7d5.png)

**Comment by deg-pl** [comment]
No, because OC NL and OC RO don't want this feature (see above)
