### ISSUE TITLE
Issues around user account activation

### ISSUE THREAD

**Issue by kojoty** [opencaching/opencaching-pl#465]
1. No contact email in the string
2. If account is activated before there should be different message than: 

![image](https://cloud.githubusercontent.com/assets/2961448/14274152/dffeaf20-fb0f-11e5-9cd8-84d47cea8bb6.png)

3. Activation process needs review and improvements to not confuse of new users

**Comment by mzylowski** [comment]
@kojoty Do you have any idea why this user had an activation problem?

**Comment by kojoty** [comment]
@mzylowski, I'm not sure but I bet the scenario that he:
- enter proper activation data and activation was done in the system
- response was lost/user close the browser windows/click something on the page what makes him not aware of successful activation
- every next try of activation for active account is handling as error

I've checked DB and everything seems to be OK.

**Comment by kojoty** [comment]
**First:**
I think we should separate the situations when:
- user enter wrong activation code
- account was activated yet

and then we will have a two separate messages for the user:
- something is wrong - contact us <email>
- your account is active - try to log in

**Second:**
if you change the polish translation file please add a changes to the english one also - I think that english translation should be common base for all translations...

**Third:**
(I wrote it in pull-request but again) In my opinion we shouldn't put any node-specific data (like email in opencaching.pl domain) in a common code - it always should be put in configuration (node-settings).

**Comment by mzylowski** [comment]
@ first
I know, we need few new messages, but:
I mentioned about 285 because it solve this at all.
When we have only link in mail we can just show success / error message after click. And we have one success message and two errors (problem with link, already activated). 
@ second
This is fix only for few days. I want to solve 285 and add new translations.
Also I mentioned Harrie and andri in my PR to inform about my temporary translations.
