### ISSUE TITLE
Maps center default from user profile (if available) or settings

### ISSUE THREAD

**Issue by harrieklomp** [opencaching/opencaching-pl#491]
When user has not set home coordinates on his profile the map on cacheguides.php (line 24 - 27) shows Poland. Can this be done via settings file?
There are map settings in settings file. Maybe these can be used?

**Comment by wloczynutka** [comment]
in settings.inc.php already is variable for set default coordinated. Please use it when work on this issue.

**Comment by harrieklomp** [comment]
I have changed it and will commit tomorrow. It works on VM.
From:
            tpl_set_var('mapcenterLat', 52.057);
            tpl_set_var('mapcenterLon', 19.07);
to:
            tpl_set_var('mapcenterLat', $main_page_map_center_lat);
            tpl_set_var('mapcenterLon', $main_page_map_center_lon);

**Comment by harrieklomp** [comment]
Done.

**Comment by andrixnet** [comment]
1. http://www.opencaching.nl/cachemap3.php shows center coordinates 0:0 (this seems to be due to the data in my profile which reads as N 00° 00.000' E 00° 00.000', though I am not sure how or why it got to be recorded as such). 

These 0 coordinates should either be treated separately or be removed from database contents (and corresponding fields be assigned to NULL and by default to NULL) until user explicitely chooses such coordinates. 
(and maybe show a highlight in the user profile that he/she did not choose coordinates)

2. Home page map is correct (shows NL)

3. Flopp's map view can be configured extensively. (look at my work for cache mini-map and links). Nodes should be able to configure center coordinates and other options on individual basis.

4. http://www.opencaching.nl/logmap.php correctly centers on BeNeLux

5. http://www.opencaching.nl/myroutes_add_map2.php incorrectly shows Poland

6. http://www.opencaching.nl/cacheguides.php correctly centers on BeNeLux

7. http://www.opencaching.nl/myneighborhood.php centers on Warsaw

8. http://www.opencaching.nl/powerTrail.php?ptAction=showAllSeries shows empty map

This is a quick review of the map centering functionality.
