### ISSUE TITLE
okapi_settings.php

### ISSUE THREAD

**Issue by deg-pl** [opencaching/opencaching-pl#514]
Shouldn't be okapi_settings.php in .gitignore?
I'd like to change ADMINS - to my e-mail address (or anything else)...

**Comment by following5** [comment]
> Shouldn't be okapi_settings.php in .gitignore?

That would make it difficulty to deploy changes like [this](https://github.com/opencaching/opencaching-pl/commit/a88d231194767d4d640d9b472e2f300a732f1180).

You can  use the `$sql_errormail` setting (in lib/settings.inc.php) to set your admin address. If there are multiple site admins, you may set it to "root@localhost" and then set aliases for the root mail account.

Generally, if OKAPI settings need to be overriden locally, they can be set in lib/settings.inc.php and then referenced by okapi_settings.php.

**Comment by deg-pl** [comment]
If I understand well - in okapi_settings first is included /lib/setting.inc.php, and next is set:
'ADMINS' => array($sql_errormail, 'rygielski@mimuw.edu.pl', 'following@online.de'),

So if I change `$sql_errormail` - you will still recieve mails from cron on my devel server (like yesterday ;) ).

I think MUCH better solution is move settings to okapi_settingsDEFAULT.php - like OCPL, and okapi_settings.php add to .gitignore.

**Comment by following5** [comment]
That would allow to create redundant local settings, because most of the entries can already be overriden in lib/settings.inc.php. It would also make OKAPI configuration somewhat more intransparent for OKAPI developers.

What about adding options to lib/settings.inc.php which allow to override DATA_LICENSE_URL and ADMINS? Then everything can be overriden locally, while keeping a maximum of consistency between all nodes' OKAPI settings.

**Comment by following5** [comment]
e.g.

```
'DATA_LICENSE_URL' => ($data_license_url ? $data_license_url : 'http://wiki.opencaching.pl/index.php/OC_PL_Conditions_of_Use',
'ADMINS' => ($okapi_admin_mailaddrs ? $okapi_admin_mailaddrs : array($sql_errormail, 'rygielski@mimuw.edu.pl', 'following@online.de'),
```

**Comment by deg-pl** [comment]
#520 will be OK?

**Comment by following5** [comment]
Ok for DATA_LICENSE_URL, but not for ADMINS: It will ignore an `$sql_errormail` setting in settings.inc.php.

**Comment by andrixnet** [comment]
Not sure how to handle this, from the point of view of http & https: 
okapi_settings.php: 
```
        'ORIGIN_URL' => (
            isset($origin_oc_url) ? $origin_oc_url :
            ($oc_nodeid == 14) ? "http://www.opencaching.nl/" :
            "http://opencaching.pl/"
        ),
```

There is no `$origin_oc_url` variable in settings.inc.php because there is no such variable in settings-example.inc.php
There is however `$absolute_server_URI`
IMO $origin_oc_url could/should be replaced by $absolute_server_URI

However I would suggest migrating to something like this: 
https://github.com/andrixnet/opencaching-pl/blob/settings/lib/settingsDefault.inc.php 
lines 136 - 145

**Comment by following5** [comment]
The ORIGIN_URL setting meanwhile has been replaced by the internally defined "[OC schema codes](https://github.com/opencaching/okapi/blob/master/okapi/core.php#L1238)". It is obsolete and can be removed from okapi_settings.php.
