### ISSUE TITLE
opencaching.us ==> new ocpl code 

### ISSUE THREAD

**Issue by Mr-Yuck** [opencaching/opencaching-pl#859]
Hello, Jim (Mr.Yuck) from opencaching.us here.  I've discussed this with Andrei from opencaching.ro, and he suggested I make a formal request here. We really need to update to the latest ocpl code, as we are the only site left on the "old", or "sp2ong"  code, which is from 2008 or 2009, I believe. Our hosting company changed a couple things late in 2016, and it's left a few things on our site broken, as well as the old code issues. Andrei helped us get the site back up, and **mostly** operational at that time.  I should note we've made several changes to the code, including 5 or 6 unique caches types, events count as finds, as well as others. All of which I can document here, if needed.

**Comment by harrieklomp** [comment]
Hi Jim, welcome here on ocpl source code. Let us not discus about cache types or counting events as a find. I am not a programmer but i know it should be possible to add new cache types and/or cache sizes and add/remove them per node. In the actual ocpl code a event does not count as a find but it should be possible to make it per node count or not count as a find.

**Comment by Opencachingna** [comment]
Hi, Harry. Yes, I meant all of our unique stuff to be per node. I'd **never** suggest the OCPL code be altered to make events count as finds. I pretty much made that change to the old code to our node only by myself.

**Comment by deg-pl** [comment]
Hi!
It will take some time (and work), but is possible to update database from 2009 to our OCPL code. A few months ago I've done it at OC UK. Please - contact me via e-mail (deg at best dot pl) or via Facebook https://www.facebook.com/grzegorz.deja . I'll need access to shell.

**Comment by andrixnet** [comment]
OCNA hosting is quite a mess. I will try to help Jim sort it out into a better organized set of sites.

**Comment by andrixnet** [comment]
Jim, migrating to OCPL-current code also means having your future website kept in sync (automatically updated) with OCPL-current changes. 
Thus all future changes must first be done in the code repository (here) and no code change must happen locally on your node. (other then the configuration file)

**Comment by Opencachingna** [comment]
@deg-pl Andrixnet said he would give you an ssh key. With my permission, which I've given. :-)

**Comment by Opencachingna** [comment]
@andrixnet I'm confused. Here you say no code changes can be done on our node, yet you opened other issues regarding the changes we'd like (and obviously already have on the old code locally).

**Comment by andrixnet** [comment]
@Opencachingna you misunderstood. 
All changes in the code are done by developers and uploaded here (Github). Once they are merged into the master, Github automatically issues a notification to each subscribed OC site. Each site then runs a script that updates it's own code based on the latest version from Github and some housekeeping. 

Any change will equally affect all subscribed sites. 

Once OCNA switches to OCPL-current, OCNA site will also be subscribed and the above mechanism will keep it updated. 
What I was saying was that once this is set up, all code changes must happen here, on GitHub, not on a single site's server, because it will break the update mechanism.

**Comment by Mr-Yuck** [comment]
I have changed my username, by the way, as some of the other OCNA Admins will probably be contributing, and I don't want to cause any confusion with me being opencachingna, and professing to speak for everyone at opencachingna. :-)

**Comment by deg-pl** [comment]
See also #7 (OC UK is also affected)

**Comment by TermiteHunter** [comment]
Hello and forgive me if speaking out of turn and for resurecting this old conversation.

It is now Feb 2019 (2 years since the last comment here) and we are still operating on an even more  broken site.
There are failures on our site that affect all users and discourages new members.

The attempt to bring OCNA into the new PL code failed long ago when we were abandoned and forgotten. Attempts to get help with a PL or DE styled update by Mr-Yuck have been met with a few promising ideas from various individuals only to be abandoned before they begin.

The OC Community is about to lose OpenCaching North America. (Mexico, US, Canada and parts of Central America)
The site looks and operates poorly, an embarasment to the OC community as a whole.
This can not continue. I find that I can no longer encourage others to explore OCNA in it's cuurent state and have even declined to list my own caches on OCNA (and I am an Admin there)

Please contact Mr-Yuck and re-instate the OCNA migration to an updated version of the OC code so that we may continue as a valued and valid OC site. 
**Need is URGENT.**
Admin at OCNA are preparing to allow this node to join Navicache and become a non-entity if help is not recieved soon.

Action is needed. 
The site is failing. (maps fail. search fails, registration fails)
Admin is discouraged. (too many promises with no follow-up and abandonment)
Use is plummeting. (new users down, listings down, logs down)
Failure is imminent. (by code failure, lack of use, or intentional failure to renew domains or hosting for a failing site)

If the goal is to have nodes in all parts of the world, The community is failing a huge part of that world.
**Save OCNA NOW**

**Comment by kojoty** [comment]
@TermiteHunter Let's close this thread and continue discussion here: #1973
