### ISSUE TITLE
Incorrect position of markers on static maps

### ISSUE THREAD

**Issue by deg-pl** [opencaching/opencaching-pl#935]
From Facebook:

> Coś się pomiąchało na mapce eventów na stronie głównej. "Centrum Zarządzania Wszechświatem wychodzi z podziemia", (woj. śląskie) pokazuje z grubsza w Białymstoku, "Hajda na Gdańsk" gdzieś na Górnym Śląsku, a podlaski "BROWAR 3" gdzieś w Trójmieście :-O

and:

> Mapa eventów na głównej dalej żyje własnym życiem :( ZIOM w Warszawie, SIO w Lublinie, a Podlasie swym zasięgiem objęło mój Gdańsk. I to tak bez referendum.

Also map on main page has the same problem (see i.e. "Wielki powrót SIO")

@miklobit could you check it?

**Comment by miklobit** [comment]
Markers positions are calculated in https://github.com/opencaching/opencaching-pl/blob/master/tpl/stdstyle/etc/write_newcaches.inc.php. 
Since calculation code had been changed long time ago and the issue seems to be quite random and data related (not occured im my dev.) i would need access to production data -> Deg: read priv. mail

**Comment by kojoty** [comment]
@deg-pl is it still an issue - it seems to work well now?
