### ISSUE TITLE
Let's switch off unused languages

### ISSUE THREAD

**Issue by deg-pl** [opencaching/opencaching-pl#975]
See OC i.e. in Swedish:
![tmp](https://cloud.githubusercontent.com/assets/13884863/25061586/37595c94-21ba-11e7-987f-6efbc5632c12.png)
I think site with so many "No translation available" has no sense!
User menu:
![tmp](https://cloud.githubusercontent.com/assets/13884863/25061601/8f9d2124-21ba-11e7-94d3-c77000f01efd.png)
Let's switch off all languages except PL, NL, RO, EN and DE (which is better, but far from ideal).

**Comment by kojoty** [comment]
+1

**Comment by harrieklomp** [comment]
:+1: 
I was planning to use English translations for not translated German translations. This will be done in the next days.

**Comment by harrieklomp** [comment]
German language is synchronised with English translations. Some very simple translations are done in German.

**Comment by kojoty** [comment]
@deg, @harrieklomp, @andrixnet,
I made a change which disable unsupported languages - now config provides list o supported languages in variable: $config[ 'supportedLanguages'] - by default: 'pl', 'en', 'nl', 'ro' languages are supported.

Every node can decide to enable another languages in their settings.inc.php but please note that then we should have a common translation files in the code + db prepared for those languages - there are many translation columns (for example take a look at table countries). This change is necessary for us because for example creation of the cache in german language generates exceptions and broke a DB (of course it should be fixed in code, but this needs much more work).

I hope we will be able to support more languages soon!

**Comment by kojoty** [comment]
I also moved all national flags from dir "images" to "images/flags" - if it breaks anything please give me know.

**Comment by kojoty** [comment]
I hope now it can be closed.

**Comment by deg-pl** [comment]
OC PL and OC UK has no "ro" support in DB (i.e. in "countries" table)  - only supports PL, EN and NL.

OC NL doesn't include settingsDefault.inc.php (I don't know why) and now returns error 500.

**Comment by kojoty** [comment]
> OC PL and OC UK has no "ro" support in DB (i.e. in "countries" table) - only supports PL, EN and NL.

so please override   $config[ 'supportedLanguages']  in settings.inc.php for them - OK?

> OC NL doesn't include settingsDefault.inc.php (I don't know why) and now returns error 500.

Grrr! I made a default settings in code - update in minutes!

**Comment by kojoty** [comment]
OK oc.nl is back now!

@harrieklomp, why don't you load settingsDefault.inc.php? If this is not a problem please just put:
`require __DIR__ . '/settingsDefault.inc.php';` at the beginning of your settings.inc.php

**Comment by harrieklomp** [comment]
I have placed `require __DIR__ . '/settingsDefault.inc.php';` on top of settings file.

**Comment by andrixnet** [comment]
In `settingsDefault.inc.php`:
Shouldn't `defaultLanguageList` also contain at most the same list as `supportedLanguages` ?

Actually, should they differ?

**Comment by kojoty** [comment]
> In settingsDefault.inc.php:
Shouldn't defaultLanguageList also contain at most the same list as supportedLanguages ?

> Actually, should they differ?

Yes, this is different:
- defaultLanguageList contains default list of languages for descriptions of new caches

- supportedLanguages are languages supported by translation system of oc node - translation files are OK, but the db-translations are complicated and for example oc.pl still don't have a proper db config for support Romanian :( (or even German). - we should remove all db-translations but... it's hard to predict when we manage to do this.

Should we unify this settings? - I think we could but it is not necessary..
