### ISSUE TITLE
MyRoutes: can't get parts of results (as many zip files) 

### ISSUE THREAD

**Issue by kojoty** [opencaching/opencaching-pl#991]
if route is assigned to more that 50 caches or user select GPX+pics button there will be open a webpage with many links to files with result parts:

![image](https://cloud.githubusercontent.com/assets/2961448/25457624/2c8e1ebe-2ad7-11e7-8913-7c7ea14ae8f0.png)

but links to the zip files are broken!

@andrixnet, those links were in format which was translated by this .htaccess rewrite rule:
RewriteRule ^ocpl(\d+)\.(gpx|kml|loc|ov2|ovl|txt|wpt|uam|xml|zip|ggz)$ search.php?queryid=$1&output=$2&%{QUERY_STRING} [NC]

to the link to the search page with proper query_id (query is saved in DB)

It was changed here:
https://github.com/opencaching/opencaching-pl/commit/d5bcc8a155d254c538cc1437afb9e0fe51b20906#diff-79b002f3f090ba2288403f721545f0a4R943
(I made comment to point to this issue).

**Comment by kojoty** [comment]
hope now it is fixed

**Comment by andrixnet** [comment]
I changed the filename due to the following reasoning: 
- `ocpl` prefix was used for most (if not all) file prefixes (whenever the object was anything but a single cache)
- also some generated filenames were broken with things like missing extension
- `ocpl` filename prefix designates either the project (not really relevant to users) or opencaching.pl site (valid for polish users, but not for all the other sites)
- `ocpl` filename prefix does not illustrate the intended purpose of the file.

Consequently I named results returned by search pages as `search1234.gpx` and results returned by my routes section as `myroute-1234.gpx` to let the user know, while futher managing his/her files (or later use), about the meaning and information source for the content. (ie results of a search or caches along a prepared route)

This is a working quick fix, however I would recommend reopening the issue and recheck all file exports for this problem and fix it by adapting the `.htaccess` rules to handle the improved naming scheme, unless there is good reason not to.
Now that I know about this, I think I can handle the rest.

**Comment by kojoty** [comment]
@andrixnet , I definitely agree that 'ocpl' is not a good name here, but the changes around search* are danger from my point of view - this is the worst, most complicated and most incomprehensible part of oc code and at the same time it is responsible for important feature which is export cache list to garmins and others devices. Our users complains and I needed to prepare fast fixes for issues pointed by them.

If you feel you want to change it - feel free to reopen this issue and prepare the final fix.
